spring.application.name=BalneaMdp

spring.datasource.url=jdbc:mysql://localhost:3306/balnear
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Cloudinary
cloudinary.cloud-name=dkdmp5wd6
cloudinary.api-key=941739451932989
cloudinary.api-secret=hDWUOshnRf82Q2OcNwZ8ggGLOOY


# Config File
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB